name: CI

"on": [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # full history for metadata
          submodules: true

      - name: Check out LFS files
        run: |
          git lfs install
          cd milestones
          git config -f .lfsconfig lfs.url https://git-lfs.lsst.cloud/lsst-dm/milestones
          git lfs pull


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          python -m pip install "pydantic<2.0.0"
          python -m pip install "lander<2.0.0"
          python -m pip install -r milestones/requirements.txt
          make generated


      - name: TeX build
        run: |
          docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'

      - name: Landing page upload
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          lander --pdf LDM-503.pdf --upload --lsstdoc LDM-503.tex --ltd-product ldm-503
